### ISSUE TITLE
Endre fra å presentere anbefalte organisasjoner til anbefalte tiltak

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#541]
Det er enklere for donor å forholde seg til konkrete tiltak som:
Malarianett
Malariamedisin
A-vitamin
Kontantoverføringer
osv, enn navnene på de faktiske organisasjonene som ikke alltid er beskrivende, slik som Helen Keller International og New Incentives. Det klargjør også at for noen organisasjoner er det ikke hele alt de gjør som er anbefalt, slik som med HKI.

- [x] Bestem hvordan vi skal kommunisere anbefalte tiltak og anbefalte organisasjoner
- [x] Identifiser hvilke deler av nettsiden som må oppdateres
- [x] Identifiser hvilke deler av backend som må oppdateres
- [x] Forbered nødvendige endringer i tekst og innhold på nettsiden
- [x] Forbered nødvendige endringer av backend
- [ ] Skriv en kort bloggpost om endringene vi gjør og hvorfor
- [x] Gjennomfør endringene
- [ ] Publiser bloggpost og del i sosiale medier, få med i neste nyhetsbrev
```[tasklist]
### Tasks
- [ ] https://github.com/stiftelsen-effekt/main-site/issues/854
```
