### ISSUE TITLE
Phase out google analytics

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#839]
Right now we use GA for _at least_ search console and tracking indirect paths for page views (e.g. front-page - _some page_ - destination page).

These functionalities should be maintained in plausible or somewhere else.
```[tasklist]
### Tasks
- [x] Put historical data in a backup sheet
- [x] Remove from privacy policy
- [x] Remove tracking id from main site
```

**Comment by fellmirr** [comment]
Data is backed up in aggregate form in our google drive in the folder "arkiv"
