### ISSUE TITLE
[MinSide.Donations] Change from pretend swedish to real swedish across the board

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#871]
```[tasklist]
### Tasks
- [ ] Title
- [ ] Men
- [ ] Sum
- [ ] Aggregated impact
- [ ] Donations table desktop
- [ ] Donations table mobile
- [ ] Donations table details
```
