### ISSUE TITLE
[Feature]: Upgrade next and sanity

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/main-site#961]
### Description

Upgrade next and sanity to latest versions (14 and 3 respectively)

```[tasklist]
### Tasks
- [ ] Fix preview
- [x] [sanity preview component] citation renderer
- [x] [sanity preview component] columns preview
- [x] [sanity preview component] contact preview
- [x] [sanity preview component] fullimage preview
- [x] [sanity preview component] fullvideo preview
- [x] [sanity preview component] htmlembed preview
- [x] [sanity preview component] katex input
- [x] [sanity preview component] katex preview
- [x] [sanity preview component] links preview
- [x] [sanity preview component] normal image preview
- [x] [sanity preview component] organizations list preview
- [x] [sanity preview component] paragraph preview
- [x] [sanity preview component] pointlist previerw
- [x] [sanity preview component] question and answer group preview
- [x] [sanity preview component] section preview
- [x] [sanity preview component] testimonials preview
- [x] fix undefined layout crash
```
